#
# Copyright (c) 2022 Rojar Smith.
#

baseurl = "https://www.bitdove.net/docs"
languageCode = "en-us"
title = "Bitdove"
theme = "hugo-material-docs"
metadataformat = "toml"
canonifyurls = false

[markup]
	[markup.goldmark]
		[markup.goldmark.extensions]
			typographer = true

[markup.highlight]
	codeFences = false

[params]
	# General information
	author = "The Bitdove Project"
	description = "IoT. Update. Device."
	copyright = "The Bitdove Project"
	logo = "images/bitdove_logo_256x256.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = ["css/bitdove.css"]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[params.palette]
	primary = "deep-purple"
	accent  = "light-green"

[params.font]
	text = "Ubuntu"
	code = "Ubuntu Mono"

[social]
	bitdove = "bitdove"

[[menu.main]]
	name   = "What is bitdove"
	url    = "/whatisbitdove/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "/gettingstarted/"
	weight = 20

[[menu.main]]
	name   = "Guides"
	url    = "/guides/"
	weight = 30

[[menu.main]]
	name   = "Features"
	url    = "/features/"
	weight = 40

[[menu.main]]
	name   = "Concepts"
	url    = "/concepts/"
	weight = 50

[[menu.main]]
	name   = "Architecture"
	url    = "/architecture/"
	weight = 60

[[menu.main]]
	name   = "Management UI"
	url    = "/ui/"
	weight = 70

[[menu.main]]
	name   = "APIs"
	url    = "/apis/"
	weight = 80

